#This is base CentOS image to create Dev Environment
FROM centos:centos7.5.1804
LABEL maintainer="devloper@abc.com"

RUN echo "Install wget and tar package"
RUN yum -y install wget
RUN yum -y install tar
